### PR TITLE
[datadog_synthetics_test] Add support for variablesFromScript for API tests

### PR DESCRIPTION
**Pull request by ruizb**
Add support for `variablesFromScript` feature for Synthetic API tests.

### CODE REVIEW

**Review by aliciascott — DISMISSED** [review]
good for docs

**Comment by nkzou** [comment]
Hey, could you add or update at least one test in https://github.com/DataDog/terraform-provider-datadog/blob/master/datadog/tests/resource_datadog_synthetics_test_test.go to use the new field?

**Comment by ruizb** [comment]
It should be good now, though I had to update a bunch of cassette files 🤔

**Comment by ruizb** [comment]
@nkzou Sorry for the direct ping, I'm not sure what's the best way to get another review on this PR 😬

**Comment by nkzou** [comment]
No worries, will review in a bit. In the future it's better to post in the #api-clients slack channel so the whole team can see it

**Review by nkzou — APPROVED** [review]

**Pull request merged**
