### PR TITLE
[datadog_user] Revert "[datadog_user] Add service account support (#1490)"

### PR DESCRIPTION
**Pull request by skarimo**
This reverts commit 26bab4cc94f391277306cadf08d67da47f3860cb.

### CODE REVIEW

**Review by therve — APPROVED** [review]

**Review by srosenthal-dd — APPROVED** [review]
Sorry for the churn! One of our PMs @louisthaboogie wants to do this slightly differently - a separate resource for `datadog_user` and `datadog_service_account` rather than a flag on datadog_user. I think @sseg-dd's team is planning to do the next iteration of this.

**Comment by jorhett** [comment]
@srosenthal-dd I'm all for taking another approach, but this support has been lacking for quite a long time now. We're stubbing around all the things that Datadog's official provider doesn't support by making our own API calls. The delay between API support and Datadog Terraform support is quite lengthy

**Comment by louisthaboogie** [comment]
@jorhett , apologies for the delay here. We are actively working on adding Service Account as of a unique resources in our Terraform integration. This should be available by the end of the quarter, hopefully much sooner.

**Comment by jorhett** [comment]
@louisthaboogie it's been a month and you've done a fairly large release since then... and nada?  Nothing in the master branch, no PRs to address this. What do you consider "actively working on" to be?

Adding to the list of reasons we're looking for alternates to DataDog.  Super high prices, low/no delivery.

**Comment by jlamande** [comment]
@louisthaboogie any PR in progress that we could track ?

That's clearly an ugly part in our code where we needed to use external/null_resource/scripts/api calls for many months.

**Comment by russwion** [comment]
We're looking for this same capability.  
@louisthaboogie Any progress towards this?
@jlamande Can you share your work around code?

**Comment by jorhett** [comment]
@russwion the PR #1685 seems to work, try it out

**Pull request merged**
