### PR TITLE
Cleanup makefile, add testall, add rerun-failed

### PR DESCRIPTION
**Pull request by nmuesch**
This PR aims to cleanup the Makefile and the way tests are run:

* Adds rerun-failed to gotestsum so we can retry individual errors
  * The default here is sane, the test will be retried twice, and if more than 10 tests are failing, tests won't be retried at all by gotestsum since there's likely a larger issue at play
  * gotestsum requires you pass in the packages to it, so I also moved the `go list` to be part of the invocation to `gotestsum` instead of `go test` flags. 
* Add a new `make testall` command that will run both acceptance and unit tests
  * Stop `make test` from running the acceptance tests in record mode
* Set the default `RECORD` to `false` in the makefile and allow it to run `make testacc` or `make testall` with the flag to control if we playback or record during testing
* Remove the special make commands for installing the provider as a plugin for terraform 0.13; we explicitly document how to do this using terraform 0.14 in the new DEVELOPMENT.md file. 
* Update the DEV doc for people to use `testall` instead of `testacc`

### CODE REVIEW

**Review by fanny-jiang — APPROVED** [review]
LGTM. The changes are pretty clear and simplifies testing commands

**Review by jirikuncar — APPROVED** [review]

**Pull request merged**
