### PR TITLE
Update go client

### PR DESCRIPTION
**Pull request by romainberger**
Update go client to latest version.

### CODE REVIEW

**Review by zippolyte — APPROVED** [review]

**Comment by skarimo** [comment]
Master should have the latest go-client. We can close this.

**Comment by romainberger** [comment]
@skarimo Is master automatically using the latest version? Because [I have a PR](https://github.com/DataDog/terraform-provider-datadog/pull/1005) that needs a newer version that seems to be currently used, so it fails (it uses an endpoint that recently added to api-spec).

**Comment by skarimo** [comment]
@romainberger Not automatically but I merged this PR https://github.com/DataDog/terraform-provider-datadog/pull/1003 yesterday that updated the client to the latest version. Took a quick pass on the other PR and am seeing `Requested interaction not found` errors which indicates you might need to re-record the cassettes for your tests. I am not seeing any missing model errorss

**Comment by romainberger** [comment]
@skarimo Ah right, I misread the errors, thank you!

**Pull request closed without merging**
