### PR TITLE
[monitor] Fix updating priorities.

### PR DESCRIPTION
**Pull request by phillip-dd**
And adds a test to cover updating priorities.

cc @DataDog/monitor-app

### CODE REVIEW

**Review by zhengshizhao — APPROVED** [review]
awesome! thanks for fixing it!

**Review by zippolyte — APPROVED** [review]

**Comment by phillip-dd** [comment]
Looks like silenced tests are failing:
```
=== FAIL: datadog TestAccDatadogMonitor_SilencedRemove (2.54s)
    testing.go:684: Step 1 error: Check failed: Check 4/4 error: datadog_monitor.foo: Attribute 'silenced.*' expected "-1", got "0"

=== FAIL: datadog TestAccDatadogMonitor_MuteUnmuteSpecificScopes
    testing.go:684: Step 1 error: After applying this step, the plan was not empty:
```

We fixed the issue around accepting `0`s in the silenced - did some other behavior break here?

**Comment by zippolyte** [comment]
I think it's not completely back to the behavior it had previously in the backend. IIUC, the backend also returned 0 in the response payload, but now returns `null` for the values where we put 0.

**Comment by zippolyte** [comment]
Regardless, I think we can merge this as it's not related to the failure

**Pull request merged**
