### PR TITLE
[resource_datadog_dashboard] add support for toplist widget styles in dashboards

### PR DESCRIPTION
**Pull request by brtu**
### Background:
This PR is backed on the api-spec change https://github.com/DataDog/datadog-api-spec/pull/3088 which adds the `palette` field to a toplist widget's style

### This PR:

- Add Terraform support for Toplist widget styles.  Style defaults to flat if not specifed
- Toplist stacked style can specify the palette, palette defaults to datadog128
- Adds tests for toplist widget with style props
- Updates relevant documentation

### To Test:

1. Set up test env according to https://datadoghq.atlassian.net/wiki/spaces/DB/pages/3218343160/Working+with+Terraform+Dashboards
2. Loaded a local Terraform config such as:
```
resource "datadog_dashboard" "top_list_dashboard" {
	title         = "{{uniq}}"
	description   = "Created using the Datadog provider in Terraform"
	layout_type   = "ordered"
	is_read_only  = "true"

	widget {
		toplist_definition {
			title_size = "16"
			title = "Toplist with flat style"
			title_align = "right"
			live_span = "1w"
			request {
				q = "top(avg:system.cpu.user{*} by {service,app_id}, 10, 'sum', 'desc')"
				conditional_formats {
					palette = "white_on_red"
					value = 15000
					comparator = ">"
				}

			}
      			custom_link {
				link = "https://app.datadoghq.com/dashboard/lists"
				label = "Test Custom Link label"
			}
			custom_link {
				link = "https://app.datadoghq.com/dashboard/lists"
				is_hidden = true
				override_label = "logs"
			}
			style {
				display {
					type = "stacked"
				}
			}

		}

	}


	widget {
		toplist_definition {
			title_size = "16"
			title = "Toplist with stacked style"
			title_align = "right"
			live_span = "1w"
			request {
				q = "top(avg:system.cpu.user{*} by {service,app_id}, 10, 'sum', 'desc')"
				conditional_formats {
					palette = "white_on_red"
					value = 15000
					comparator = ">"
				}
			}
      			custom_link {
				link = "https://app.datadoghq.com/dashboard/lists"
				label = "Test Custom Link label"
			}
			custom_link {
				link = "https://app.datadoghq.com/dashboard/lists"
				is_hidden = true
				override_label = "logs"
			}
			style {
				display {
					type = "stacked"
				}
			}
		}
	}
}
```
3. Used `terraform apply`
4. Noted dashboard with toplist widgets with styles were created on test env
5. Also ran unit tests via
```
% DD_TEST_CLIENT_API_KEY="api-key" DD_TEST_CLIENT_APP_KEY="app-key" TESTARGS="-run TestAccDatadogDashboardTopListWithStyle" RECORD=true make testacc
```

### CODE REVIEW

**Review by hestonhoffman — DISMISSED** [review]

**Comment by brtu** [comment]
Removed the `go.mod` and `go.sum` changes

**Review by hyungl — DISMISSED** [review]
LGTM but looks like there are conflicting go versions causing checks to fail

**Comment by brtu** [comment]
@hyungl ah yep, goimports had a release yesterday which is why it has that go version error.  api-clients team is aware of the issue

**Review by hestonhoffman — APPROVED** [review]

**Comment by brtu** [comment]
@hestonhoffman @hyungl sorry to re-request reviews on this... will stop rebasing and just merge from now on

**Review by amaskara-dd — APPROVED** [review]

**Pull request merged**
