### PR TITLE
New data sources for widgets

### PR DESCRIPTION
**Pull request by roughbits01**
Add security signals and RUM events as data sources for Timeseries, Query Value, Table and Top List dashboard widgets.

This PR is related to this [go api PR](https://github.com/zorkian/go-datadog-api/pull/304). It will be merged with the version bump after go api PR is merged and a new version is released.

### CODE REVIEW

**Comment by roughbits01** [comment]
@jirikuncar I will 🙂

**Comment by roughbits01** [comment]
@jirikuncar done :)

**Comment by bkabrda** [comment]
Hey @roughbits01, yesterday I merged an update to the latest version of go-datadog-api to master, so when you rebase, everything should start working. Additionally, I'd like to ask you to update the testing cassette for timeboards (a cassette is basically a set of pre-recorded API requests and responses that allows us to test offline and fast). Instructions on how to do this are in [README.md](https://github.com/terraform-providers/terraform-provider-datadog/#developing-the-provider).

If you have any issues with regenerating the cassette, please let me know and I'll help. Thanks!

**Comment by roughbits01** [comment]
Hi @bkabrda, I'll update the PR this week 🙂 Thank you for your reply.

**Pull request merged**
