### PR TITLE
[datadog_synthetics_test] Add missing disable_cors option

### LINKED ISSUE #1602: synthetics_test: add option to disableCors
### Terraform Version
```
Terraform v1.3.1
on linux_amd64
+ provider registry.terraform.io/datadog/datadog v3.7.0
```

### Affected Resource(s)
- synthetics_test

### Expected Behavior

An option to `disable_cors` should be present in the `options_list` block. Similar to `disable_csp`, as documented [here](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/synthetics_test#disable_csp).

### Actual Behavior

No such option is present.

### Important Factoids
I am working on a PR right now

### PR DESCRIPTION
**Pull request by JordanP**
Add support for  `disable_cors` option for Synthetics tests.

Fixes #1602

### CODE REVIEW

**Comment by JordanP** [comment]
CC @romainberger @urseberry @skarimo

**Review by jtappa — APPROVED** [review]
👍🏻 from docs team

**Review by romainberger — APPROVED** [review]

**Comment by JordanP** [comment]
Hum I am not sure what I can/should do about these CI / Workflows failures.

**Comment by nkzou** [comment]
Hi there, going to continue this in #1605 due to the CI having permissions issues with your fork. Thanks for your contribution!

**Pull request closed without merging**
