### PR TITLE
Correct the spelling of dashboard in a private function

### PR DESCRIPTION
**Pull request by brandoncole**
While reading through the code I happened to notice a function had a small misspelling

- `s/boar/board/`

...unless Datadog plans to change the dog 🐶  to a boar 🐗 in an upcoming marketing rebranding.

### CODE REVIEW

**Review by nmuesch — APPROVED** [review]
Haha, thanks for the fix! 🙂
🚀

**Review by DrkSephy — APPROVED** [review]

**Comment by brandoncole** [comment]
Looks like a connectivity glitch on the #IntegrationTests stage in `DataDog.terraform-provider-datadog` from the looks of the logs.  If it's easier for me to push another commit let me know unless the pipeline can just easily be rerun on your side.

**Comment by nmuesch** [comment]
Hey, I took a look and it appears to be due to the way azure pipelines runs CI from forks. I'll take a look at this one again tomorrow. Sorry about that

**Pull request merged**
