### PR TITLE
Bump datadog-api-client-go and deprecate `agent_rule` field

### PR DESCRIPTION
**Pull request by jirikuncar**

### CODE REVIEW

**Review by andpiccione — COMMENTED** [review]
Thanks for removing this 🙇 LGTM, but shouldn't we also modify tests&cassettes and update documentation accordingly?

**Review by andpiccione — APPROVED** [review]
👍 Can you also re-run `make docs`? I think markdown files should be updated following the field deprecation

**Review by therve — APPROVED** [review]

**Pull request merged**
