### PR TITLE
datadog_synthetics_test: device_ids is required for browser type only

### PR DESCRIPTION
**Pull request by alexjurkiewicz**
update of #1215

If you don't specify this property, you'll see the following error:

> 400 Bad Request: {"errors": ["properties.options.required: 'device_ids' is a required property...

### CODE REVIEW

**Review by zippolyte — COMMENTED** [review]
Unfortunately, that won't work either.
The docs are generated automatically based on the schema defined in https://github.com/DataDog/terraform-provider-datadog/blob/4e7641455dd44cd847575171c23bdf3116b7dd72/datadog/resource_datadog_synthetics_test_.go#L25

So it's not possible to discriminate attributes unfortunately. The best we can do is add in the description itself that it is required.

**Review by zippolyte — CHANGES_REQUESTED** [review]
I suggest adding some wording here to emphasise that it is required for browser tests 
https://github.com/DataDog/terraform-provider-datadog/blob/4e7641455dd44cd847575171c23bdf3116b7dd72/datadog/resource_datadog_synthetics_test_.go#L69

**Review by kayayarai — APPROVED** [review]

**Comment by alexjurkiewicz** [comment]
Updated as suggested -- thanks for pointing out how the docs are autogenerated 👍 .

**Review by zippolyte — COMMENTED** [review]
Looks good, thanks !
Can you just run `make docs` to generate the new changes.
I can do it otherwise and push on your branch if your having issues running it

**Review by zippolyte — APPROVED** [review]

**Review by cswatt — APPROVED** [review]

**Pull request merged**
