### PR TITLE
[datadog_service_account] Role-assignment improvements for service accounts

### PR DESCRIPTION
**Pull request by retsguj**
https://datadoghq.atlassian.net/browse/ACCESS-2568

`datadog_user_role` already allows for roles to be assigned to service accounts, luckily.

### CODE REVIEW

**Comment by retsguj** [comment]
Am having a hard time figuring out what I broke in the tests...

**Review by srosenthal-dd — APPROVED** [review]
✅ I tested locally the scenarios that I cared about:

Assigning and unassigning a role to a service account with `datadog_user_role`:
```
resource "datadog_user_role" "dur1" {
  role_id = data.datadog_role.admin.id
  user_id = data.datadog_user.svc_acct_2.id
}
```

Updating the roles on a service account with `datadog_service_account`:
```
resource datadog_service_account svc_acct_2 {
  email = "stephen.rosenthal+tf-test-2@datadoghq.com"
  name  = "Stephen TF test 2"
  roles = [data.datadog_role.admin.id] # or [data.datadog_role.admin2.id]
}
```
... and ensuring that additions happen before removals, and the roles can be omitted and set via datadog_user_role instead.


One suggestion: can you update the docs that talk about "Conflicts may occur if used together with" to refer to both `datadog_user` and `datadog_service_account`? It looks like the source for that is https://github.com/DataDog/terraform-provider-datadog/blob/835587c96b716cbd9f4b63951bb10bf5fbdd0f43/datadog/fwprovider/resource_datadog_user_role.go#L51 but it's also in a (generated?) Markdown file

**Comment by srosenthal-dd** [comment]
(I'm also not sure about the test failures at a glance, looks like you'll have to read them in more detail)

**Review by brett0000FF — APPROVED** [review]

**Review by brett0000FF — APPROVED** [review]

**Review by wangwillson1 — APPROVED** [review]
code looks good to me, and basic functionality works too (assigning roles to service accounts without overwriting, creating new service accounts with/without roles)

i wasn't able to get the `exact_match` attribute working on my machine for reasons unknown, so i would appreciate if someone else could test for me 😄

**Comment by srosenthal-dd** [comment]
✅ Re-tested locally today with the latest code and it worked well for me. Good to ship as far as I'm concerned.

**Review by michaelcretzman — APPROVED** [review]

**Review by nkzou — APPROVED** [review]

**Pull request merged**
