### PR TITLE
[Synthetics] Add support for websocket synthetics tests

### PR DESCRIPTION
**Pull request by AlaricCalmette**
Add support for websocket synthetics tests

### CODE REVIEW

**Review by ruthnaebeck — DISMISSED** [review]
👍  for docs

**Review by zippolyte — CHANGES_REQUESTED** [review]
Looks good, but you need to upgrade the go client for this to work
`make update-go-client && make docs`

**Review by ruthnaebeck — APPROVED** [review]

**Comment by AlaricCalmette** [comment]
@zippolyte I updated the go client but got no changes rerendering the doc

**Review by therve — APPROVED** [review]

**Pull request merged**
