### PR TITLE
[msl] Add reflow_type property for dashboards

### PR DESCRIPTION
**Pull request by DavidRobertAnsart**
This PR adds the `reflow_type` property to dashboards. (enum with values 'auto' or 'fixed').

**Note:** to not merge now, multi-size layout is not generally available yet.
**Related PRs:**
- https://github.com/DataDog/dogweb/pull/54232
- https://github.com/DataDog/datadog-api-spec/pull/908

### CODE REVIEW

**Review by DrkSephy — COMMENTED** [review]
Thanks for working on this! The changes overall look good to me, but there is something I noticed:

If I add`reflow_type: fixed`, everything works as expected. However, using `reflow_type=auto` as follows:

```
resource "datadog_dashboard" "ordered_dashboard" {
  title        = "David's Ordered Layout Dashboard"
  description  = "Created using the Datadog provider in Terraform"
  layout_type  = "ordered"
  is_read_only = true
  reflow_type  = "auto"
  widget {
    note_definition {
      tick_pos         = "50%"
      show_tick        = false
      tick_edge        = "bottom"
      text_align       = "center"
      content          = "## Hello from Terraform!"
      font_size        = "14"
      background_color = "yellow"
    }
    widget_layout {
      width  = 12
      height = 1
      x      = 0
      y      = 0
    }
  }
  widget {
    group_definition {
      title       = "My first group"
      layout_type = "ordered"
      widget {
        timeseries_definition {
          title       = "A simple timeseries"
          title_size  = "16"
          title_align = "left"
          show_legend = true
          request {
            q            = "avg:system.cpu.user{*}"
            display_type = "line"
            style {
              palette    = "warm"
              line_type  = "solid"
              line_width = "thin"
            }
          }
        }
        widget_layout {
          width  = 6
          height = 2
          x      = 0
          y      = 0
        }
      }
    }
    widget_layout {
      width  = 6
      height = 3
      x      = 0
      y      = 1
    }
  }
}
```

This leads to an invalid request:

```
Error: error updating dashboard: 400 Bad Request: {"errors": ["Invalid widget at position 0 of type note. Error: MSL widget out of grid. Additional properties are not allowed (u'y', u'width', u'height', u'x' were unexpected)"]}
```

**Comment by DavidRobertAnsart** [comment]
> Thanks for working on this! The changes overall look good to me, but there is something I noticed:
> 
> If I add`reflow_type: fixed`, everything works as expected. However, using `reflow_type=auto` as follows,
> [...]
> This leads to an invalid request:
> 
> ```
> Error: error updating dashboard: 400 Bad Request: {"errors": ["Invalid widget at position 0 of type note. Error: MSL widget out of grid. Additional properties are not allowed (u'y', u'width', u'height', u'x' were unexpected)"]}
> ```

Yes, this is expected... When using `reflow_type=auto`, widgets should not have layouts. So the backend throw an error.
I don't know with Terraform what's possible to do:
- Add a better error message asking to remove the layouts?
- Is it possible to validate the dashboard or remove the layouts before sending the request?
- Is it possible to makes widgets schema depends on the reflow type?

**Comment by DavidRobertAnsart** [comment]
I updated the doc of the `reflow_type` property to the following:
> The reflow type of a multi-size layout dashboard. Set this only when layout type is ‘ordered’. If set to ‘fixed’, the dashboard expect all widgets to have a layout, and if it’s set to ‘auto’, widgets should not have layouts.

Possible errors messages:
1. reflow type is set when layout type is free: `Additional properties are not allowed (u'reflow_type' was unexpected)`.
2. reflow type is `fixed` and there's a missing layout: `Invalid widget at position 0 of type note. Error: MSL widget out of grid. None is not of type 'object'`.
3. reflow type is `auto` and there's a layout defined: `Invalid widget at position 0 of type note. Error: MSL widget out of grid. Additional properties are not allowed (u'y', u'width', u'height', u'x' were unexpected)`.
 
Better error messages for dogweb:
- For error 2: `Invalid widget at position 0 of type note. Error: MSL widget out of grid. 'Layout' object is missing`.
- For error 3: `Invalid widget at position 0 of type note. Error: MSL widget out of grid. 'Layout' should not be defined`.

**Review by DrkSephy — APPROVED** [review]

**Comment by skarimo** [comment]
👋  Quick question, is a default value assigned by the backend if `reflow_type` is omitted?

**Comment by DavidRobertAnsart** [comment]
> 👋 Quick question, is a default value assigned by the backend if `reflow_type` is omitted?

If `reflow_type` is omitted, a `null` value is used and the frontend will guess with the missing reflow_type with the widget layouts in the board: if no widgets have a layout the reflow will be 'auto' otherwise it will be 'fixed'.

**Review by therve — APPROVED** [review]

**Pull request merged**
