### PR TITLE
Upgrade to go v1.13.1

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by chenrui333** [comment]
```
$ make test
==> Checking that code complies with gofmt requirements...
go test -i $(go list ./... |grep -v 'vendor') || exit 1
echo $(go list ./... |grep -v 'vendor') | \
		xargs -t -n4 go test  -timeout=30s -parallel=4
go test -timeout=30s -parallel=4 github.com/terraform-providers/terraform-provider-datadog github.com/terraform-providers/terraform-provider-datadog/datadog
?   	github.com/terraform-providers/terraform-provider-datadog	[no test files]
ok  	github.com/terraform-providers/terraform-provider-datadog/datadog	0.274s
```

**Comment by chenrui333** [comment]
```
$ make test
==> Checking that code complies with gofmt requirements...
go test -i $(go list ./... |grep -v 'vendor') || exit 1
go: downloading github.com/hashicorp/terraform-config-inspect v0.0.0-20190821133035-82a99dc22ef4
go: extracting github.com/hashicorp/terraform-config-inspect v0.0.0-20190821133035-82a99dc22ef4
go: downloading github.com/hashicorp/hcl2 v0.0.0-20191002203319-fb75b3253c80
go: extracting github.com/hashicorp/hcl2 v0.0.0-20191002203319-fb75b3253c80
go: downloading github.com/go-test/deep v1.0.3
go: extracting github.com/go-test/deep v1.0.3
go: finding github.com/hashicorp/terraform-config-inspect v0.0.0-20190821133035-82a99dc22ef4
echo $(go list ./... |grep -v 'vendor') | \
		xargs -t -n4 go test  -timeout=30s -parallel=4
go test -timeout=30s -parallel=4 github.com/terraform-providers/terraform-provider-datadog github.com/terraform-providers/terraform-provider-datadog/datadog
?   	github.com/terraform-providers/terraform-provider-datadog	[no test files]
ok  	github.com/terraform-providers/terraform-provider-datadog/datadog	0.224s
```

**Comment by bkabrda** [comment]
Thanks for sending this PR! I'm ok with updating to newer Go version, but there are some merge conflicts. Could you please rebase?

**Comment by bkabrda** [comment]
Hey @chenrui333 are you still interested in following up on this PR? If not, I'm going to go ahead and close it in couple of days and open a new one that can be merged. Thanks!

**Comment by bkabrda** [comment]
Hey 👋 so since this repo is now under the DataDog org and we are in control of the build/release process (and anyone can use [goreleaser](https://goreleaser.com/quick-start/) to build the provider for themselves using go 1.11+), I'm closing this. I've also removed the `.go-version` file in #598, as it's no longer necessary.

FTR, we're currently doing official builds with [go 1.14](https://github.com/DataDog/terraform-provider-datadog/commit/d13986961f0e787d604ff0744f05687379cde685#diff-56c30d9224897b08c28075052d4595c5R18).

**Comment by chenrui333** [comment]
> Hey 👋 so since this repo is now under the DataDog org and we are in control of the build/release process (and anyone can use [goreleaser](https://goreleaser.com/quick-start/) to build the provider for themselves using go 1.11+), I'm closing this. I've also removed the `.go-version` file in #598, as it's no longer necessary.
> 
> FTR, we're currently doing official builds with [go 1.14](https://github.com/DataDog/terraform-provider-datadog/commit/d13986961f0e787d604ff0744f05687379cde685#diff-56c30d9224897b08c28075052d4595c5R18).

Interesting, how did you folks migrate the terraform provider? Is this repo going to be in the provider registry? Thanks!

**Comment by bkabrda** [comment]
@chenrui333 this migration was initiated by Hashicorp and the same will be happening for a lot of other providers that will be transferred to the orgs that own the technologies that providers work with. We're taking some final steps to have the provider be present in the Terraform Registry, so please stay tuned for that. Hope this answers your question.

**Pull request closed without merging**
