### PR TITLE
Remove deprecated ExistsFunc usage

### PR DESCRIPTION
**Pull request by zippolyte**
cf https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html#deprecation-of-helper-schema-existsfunc
This deprecation is is SDK v2, but the alternative works just fine with our SDK version

### CODE REVIEW

**Review by nmuesch — APPROVED** [review]
Thanks, the migration of exists into read looks pretty clean to me 💯 
Sorry, the conflicts are likely me adding descriptions to the top level of the resources. Let me know if you want a hand with resolving those

**Comment by zippolyte** [comment]
Wouldn't have happened if go's formatting didn't force alignement of values 😡

**Review by nmuesch — APPROVED** [review]
LGTM, thanks!!

**Comment by zippolyte** [comment]
Merging, we'll deal with the silence test in a different PR

**Pull request merged**
