### PR TITLE
[VIZZ-953] Add timeseries dual y-axis to provider

### PR DESCRIPTION
**Pull request by sighrobot**
Adds support for dual y-axis for timeseries widgets

Related:
https://github.com/DataDog/datadog-api-spec/pull/593
https://github.com/DataDog/dogweb/pull/47456

### CODE REVIEW

**Review by nmuesch — DISMISSED** [review]
Thanks, this looks good to me. 

One minor nit, it may be worthwhile to set one of the on_right_yaxis to "false" so we're testing both conditions.

**Review by therve — APPROVED** [review]

**Pull request merged**
